### ISSUE TITLE
Add some docs in code

### ISSUE THREAD

**Issue by hem1t** [maviek/fire-lang#1]
It's hard to read and understand the codes without comments, try adding some.

**Comment by maxcohn** [comment]
Some documentation in the code would be awesome, and also a brief overview about what your technique for compilation is. I can't tell, but it looks kind of like you transpile to Python and then uses PyInstaller to create an executable. I like the implementation a lot, very clever.

If you'd let me, I'd love to write some documentation for this project, just let me know and I'll get started.

**Comment by maviek** [comment]
For now I'm taking a break from this project (I'm on vacation). I was thinking about compiling to C. If you want to help, add me on the Discord: `maviek#0091`. That will be more convenient.

**Comment by hem1t** [comment]
Ok Discord says, you hired any samurai to kill friend requests.

**Comment by maviek** [comment]
Oops I forgot xD. I added you.

**Comment by maxcohn** [comment]
My tag is korlor#8544
